---
- name: Prompt for user input
  hosts: localhost
  vars_prompt:
    - name: user_name
      prompt: Enter your user name
      private: no
    - name: password
      prompt: Enter your password
      private: yes
  tasks:
    - name: displaying username and passwords
      debug:
        msg:

          - "The username is {{ user_name}}"
          - "The password is {{ password }}"