
- name: Collects variable from variable.yml file
  hosts: localhost
  vars_files: variable.yml
  tasks:

        msg:
          - "My name is {{ name }}"
          - "This is {{ course }} tutorial"
          - "We are learning about {{ chapter }}"